Servo struct
hydronautics-team/Manipulator_code pull request #1
Opened 2024-12-21 16:12 UTC by glebmih

Added servo struct, feedback by speed

2025-01-03 16:36 UTC, SeaJackal requested changes

2025-01-03 16:36 UTC, SeaJackal commented on Core/Inc/Servo.h
> +#define TIM_PWM_COUNTER 399
Если макрос доступен наружу, то имя у него должно содержать префикс HYDROSERVO

2025-01-03 16:36 UTC, SeaJackal commented on Core/Inc/Servo.h
> +	GPIO_TypeDef *GPIOx;
По имени поля хотелось бы мочь понять, что оно в себе хранит

2025-01-03 16:36 UTC, SeaJackal commented on Core/Inc/Servo.h
> +#define TIM_PWM_COUNTER 399
А если не доступен, то должен быть объявлен в .c файле

2025-01-03 16:36 UTC, SeaJackal commented on Core/Inc/Servo.h
> + * Servo.h
Имена файлов обычно пишут с маленькой буквы

2025-01-03 16:36 UTC, SeaJackal commented on Core/Inc/Servo.h
> +void hydroservo_Init(HydroServo *hydroservo_self, TIM_HandleTypeDef *htim_pwm,
У аргументов я бы не писал имена с префиксом, их просто потом долго вбивать в коде. По слову self в целом понятно, что это сам хендлер сервы

2025-01-03 16:36 UTC, SeaJackal commented on Core/Inc/Servo.h
> +void hydroservo_Init(HydroServo *hydroservo_self, TIM_HandleTypeDef *htim_pwm,
Но это дело вкуса на самом деле

2025-01-03 16:36 UTC, SeaJackal commented on Core/Inc/Servo.h
> +void hydroservo_Callback(HydroServo *hydroservo_self);
Неплохо бы пояснить, что за callback в названии

2025-01-03 16:36 UTC, SeaJackal commented on Core/Src/Servo.c
> +
Я бы советовал в начале писать объявления функций, а определения в конце файла. Так как будто легче смотреть, что вообще в этом файле есть

2025-01-03 16:36 UTC, SeaJackal commented on Core/Inc/Servo.h
> +	int16_t direction;
Непонятно, зачем 16 битная переменная для поля с двумя возможными значениями

2025-01-03 16:36 UTC, SeaJackal commented on Core/Src/Servo.c
> +	if(hydroservo_self->direction == 1)
У тебя есть переменная direction, но чтобы с ней разобраться ты всё равно делаешь if else. Мне кажется, что лучше тогда хранить скорость в виде знакового числа и использовать её здесь. Это дискуссионно, конечно, но я бы сделал так. Но нужно проверить, что скорость укладывается в знаковую переменную

2025-01-03 16:36 UTC, SeaJackal commented on Core/Src/Servo.c
> +void hydroservo_Init(HydroServo *hydroservo_self, TIM_HandleTypeDef *htim_pwm,
Этот метод в начале файла бы написать

2025-01-03 16:36 UTC, SeaJackal commented on Core/Src/Servo.c
> +void hydroservo_Init(HydroServo *hydroservo_self, TIM_HandleTypeDef *htim_pwm,
После объявления локальных функций

2025-01-03 16:36 UTC, SeaJackal commented on Core/Src/Servo.c
> +	return hydroservo_self->current_angle;
Здесь было бы здорово сделать пересчёт в градусы. Только без float. Подбери такие единицы измерения, чтобы углы были целыми. Например, миллиградусы. Для перевода можешь макрос сделать. И у метода подписать, что это Raw угол. А функцию угла в градусах можешь сделать или оставить макрос публичным. Не могу тебе сказать, как лучше

2025-01-03 16:36 UTC, SeaJackal commented on Core/Src/main.c
> +uint16_t period1;
А это что за переменные? Зачем они нужны?

2025-01-05 16:16 UTC, glebmih commented on Core/Inc/Servo.h
> +#define TIM_PWM_COUNTER 399
Название я поправил. Этот макрос равен числу переполнения счетчика у таймера для генерации ШИМ, используется в функциях сервы. Может мне его лучше объявить в main.h?

2025-01-05 16:16 UTC, glebmih commented on Core/Inc/Servo.h
> +	GPIO_TypeDef *GPIOx;
Исправил

2025-01-05 16:16 UTC, glebmih commented on Core/Inc/Servo.h
> + * Servo.h
Исправил

2025-01-05 16:16 UTC, glebmih commented on Core/Inc/Servo.h
> +void hydroservo_Init(HydroServo *hydroservo_self, TIM_HandleTypeDef *htim_pwm,
Согласен, исправил

2025-01-05 16:16 UTC, glebmih commented on Core/Inc/Servo.h
> +void hydroservo_Callback(HydroServo *hydroservo_self);
Исправил

2025-01-05 16:16 UTC, glebmih commented on Core/Src/Servo.c
> +
Компилятор такой вариант не принимает, поэтому оставил include в начале.

2025-01-05 16:16 UTC, glebmih commented on Core/Inc/Servo.h
> +	int16_t direction;
Исправил

2025-01-05 16:17 UTC, glebmih commented on Core/Src/Servo.c
> +	if(hydroservo_self->direction == 1)
Согласен, но тут есть один момент: вырождение в нуле. Скорость я задаю в виде скважности ШИМ сигнала, при значении равном 0, скорость максимальна, а направление определить не получится, если мы скорость задаем знаковой переменной. Можно сдвинуть диапазон значений на 1, чтобы скорость задавалась от 1 до 400 и от -1 до -400, а в функции изменения ШИМ вычитать эту единицу. Как думаешь это нормальное решение? Или лучше оставить отдельную переменную под определение направления?

2025-01-05 16:17 UTC, glebmih commented on Core/Src/Servo.c
> +void hydroservo_Init(HydroServo *hydroservo_self, TIM_HandleTypeDef *htim_pwm,
Исправил

2025-01-05 16:17 UTC, glebmih commented on Core/Src/Servo.c
> +	return hydroservo_self->current_angle;
Нюанс в том, что у редукторов разное передаточное соотношение, следовательно нам нужно либо добавлять в структуру сервы информацию об этом, либо передавать в функцию дополнительные переменные. Как лучше? Или вообще делать это в main?

2025-01-05 16:17 UTC, glebmih commented on Core/Src/main.c
> +uint16_t period1;
Нужны были для тестирования платы, убрал их

2025-01-06 16:44 UTC, SeaJackal commented on Core/Inc/Servo.h
> +#define TIM_PWM_COUNTER 399
Это число у тебя задаёт базовую скорость сервы? Она зависит от настроек таймера, верно? В main.h объявлять макросы, которые будет использовать твой модуль точно не нужно, если она зависит от настроек в main, то передай его в конструктор явно. Явное лучше неявного

2025-01-06 16:46 UTC, SeaJackal commented on Core/Src/Servo.c
> +
Нет, в плане после include, define и всего остального препроцессора. Дальше объявление локальных функций, дальше все глобальные, дальше определения локальных функций

2025-01-06 17:00 UTC, SeaJackal commented on Core/Src/Servo.c
> +	if(hydroservo_self->direction == 1)
Лучше сделать так, чтобы у тебя в переменной с названием скорость хранилось значение, которое ведёт себя как скорость. Даже если оно в условных единицах, нужно, чтобы 0 означало нулевую скорость и чтобы модуль скорости увеличивался с ростом модуля этого числа. Так просто будет более читаемо. А дальше сделать макрос пересчёта в том месте, где это нужно. Лио нужно переименовать переменную и считать её сразу, что чуть более оптимально по производительности, но менее читаемо и создаёт вопрос о направлении, который ты задал. Я бы сделал нормальную скорость

2025-01-06 17:03 UTC, SeaJackal commented on Core/Src/Servo.c
> +	return hydroservo_self->current_angle;
Лучше в структуру, потому что это свойство сервы, которое не будет меняться со временем. И в main это лучше не надо, потому что это зона ответственности сервы - выдать тебе нормальный угол

2025-01-18 13:03 UTC, glebmih commented on Core/Inc/Servo.h
> +#define TIM_PWM_COUNTER 399
Поправил, теперь это число передаю в структуру

2025-01-18 13:03 UTC, glebmih commented on Core/Src/Servo.c
> +
Исправил

2025-01-18 13:03 UTC, glebmih commented on Core/Src/Servo.c
> +	if(hydroservo_self->direction == 1)
Сделал

2025-01-18 13:03 UTC, glebmih commented on Core/Src/Servo.c
> +	return hydroservo_self->current_angle;
Сделал

2025-01-18 16:08 UTC, SeaJackal approved these changes

2025-01-18 17:01 UTC, merged